name:                sdl3-mixer
version:             0.1.0.0
synopsis:            Haskell bindings for SDL3_Mixer
author:              Axis Sivitz
maintainer:          aosivitz@gmail.com
copyright:           2026 Axis Sivitz

ghc-options: -Wall -Werror=incomplete-patterns -Wunused-packages -Werror=unused-packages

dependencies:
  - base

default-extensions:
  - BlockArguments

library:
  verbatim:
    default-language: GHC2021
  source-dirs: src
  when:
    - condition: "flag(pkgconfig)"
      pkgconfig-depends:
        - sdl3 >=3.4.0
        - sdl3-mixer >=3.2.4

  c-sources: []

  include-dirs:
    SDL_mixer/include/SDL3_mixer/

  exposed-modules: 
    - SDL.Mixer.Raw
  dependencies: []

flags:
  pkgconfig:
    description: Use pkgconfig to resolve SDL3_mixer dependency
    manual: true
    default: true
